### ISSUE TITLE
get_one query fails on where with multiple keys

### ISSUE THREAD

**Issue by johncsnyder** [m-housh/asyncpg-simpleorm#2]
* asyncpg-simpleorm version: 0.1.2
* Python version: 3.6.3
* Operating System: OS X

### Description

I believe theres a typo in `asyncpg-simpleorm/statements/__init__.py:190`:

```
...
        return ' AND'.join(strings), tuple(args)
```

Need `' AND '` instead.

Minimal example:

Same as your `user.py` example, just changed  `get_foo_user` -->

```
async def get_foo_user():
    print(await User.get_one(name='foo', email='foo@example.com'))
``` 

```
#!/usr/bin/env python
import os
import uuid

import asyncpg
from asyncpg_simpleorm import AsyncModel, Column, PoolManager

DB_USERNAME = os.environ.get('DB_USERNAME', 'postgres')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_HOST = os.environ.get('DB_HOST', 'postgres')
DB_PORT = os.environ.get('DB_PORT', '5432')
DB_NAME = os.environ.get('DB_NAME', 'postgres')

# We use a ``PoolManager`` here, because all classes will
# share the same manager class.
manager = PoolManager(
    user=DB_USERNAME,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME)


class DbModel(AsyncModel, connection=manager):
    """Base database model class that we inherit from.

    Adds the ``id`` column to all models that inherit from this class.  The
    ``id`` in the database will be found at a column named ``_id``.

    """
    id = Column('_id', default=uuid.uuid4, primary_key=True)


from examples.db import DbModel
from asyncpg_simpleorm import Column


async def delete_users_table(conn) -> None:
    await conn.execute('DROP TABLE IF EXISTS users')


async def create_users_table(conn) -> None:
    await conn.execute('''
        CREATE TABLE IF NOT EXISTS users (
            _id uuid PRIMARY KEY NOT NULL,
            name text NOT NULL,
            email text
        )
    ''')


class User(DbModel):
    """A simple user class.

    Table Columns
    -------------

    _id : uuid  Primary Key
    name : text  Not Null
    email : text

    """
    # Set the database tablename.  If not supplied then it defaults
    # to lower case version of class name.
    __tablename__ = 'users'

    name = Column()
    email = Column()


async def create_table():
    async with User.connection() as conn:
        await delete_users_table(conn)
        await create_users_table(conn)


async def create_some_users():
    for name in ['foo', 'bar', 'baz']:
        u = User(name=name, email=f'{name}@example.com')
        print(f'Saving user: {u}')
        await u.save()


async def get_foo_user():
    print(await User.get_one(name='foo', email='foo@example.com'))


async def delete_all_users():
    for u in await User.get(records=False):
        print(f'Deleting user: {u}')
        await u.delete()


async def main():

    await create_table()

    print("\n\nLet's create some users...")
    await create_some_users()

    print('\n\nGetting users as asyncpg.Records...')
    await get_users_as_records()

    print('\n\nGetting users as User instances...')
    await get_users_as_instances()

    print("\n\nGetting 'foo' user")
    await get_foo_user()

    print('\n\nDeleting users...')
    await delete_all_users()

    print('\n\nDropping users table...')
    async with User.connection() as conn:
        await delete_users_table(conn)


if __name__ == '__main__':
    import asyncio
    asyncio.get_event_loop().run_until_complete(main())
```

Gives me the following error:

```
...
Getting 'foo' user
Traceback (most recent call last):
  File "user.py", line 137, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "user.py", line 123, in main
    await get_foo_user()
  File "user.py", line 100, in get_foo_user
    print(await User.get_one(name='foo', email='foo@example.com'))
  File "/usr/local/lib/python3.6/site-packages/asyncpg_simpleorm/async_model.py", line 492, in get_one
    res = await conn.fetchrow(*stmt)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 379, in fetchrow
    data = await self._execute(query, args, 1, timeout)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 1289, in _execute
    query, args, limit, timeout, return_status=return_status)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 1297, in __execute
    return await self._do_execute(query, executor, timeout)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 1309, in _do_execute
    stmt = await self._get_statement(query, None)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 286, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "ANDusers"
```

**Comment by johncsnyder** [comment]
Fyi, i'm also happy to contribute and make PRs

**Comment by m-housh** [comment]
PRs are welcome.  I'll look into it when I get a chance.  I should've written a test for this type of query, but it does not look like I did.

**Comment by m-housh** [comment]
FWIW I think my original intention was to later add an `and` clause. So that a query like you were doing would like, however I moved on to other projects.

`User.get_one(name='foo').and(email='foo@example.com')`

**Comment by johncsnyder** [comment]
I see. Ive forked for now . I'll think on it and can make a PR at some point
